export const SIDEBAR_STORAGE_KEY = "main_sidebar"
export const ORGANIZATION_STORAGE_KEY = "selected_organization_id"
export const NOTE_SEARCH_STORAGE_KEY = "note_search_query"
export const NOTES_EXPANDED_STORAGE_KEY = "notes_expanded"
export const SIDEBAR_WIDTH_STORAGE_KEY = "sidebar_width"
export const ACTIVE_NOTE_ID_STORAGE_KEY = "active_note_id"
export const NOTES_STATUS_STORAGE_KEY = "notes_status"
